### ISSUE TITLE
Ability to help to recognize "What's part changed" correctly

### ISSUE THREAD

**Issue by Quramy** [reg-viz/reg-cli#90]
Naive difference detection engines (e.g. pixel-matching) sometimes don't work well.

For instance, someone committed with message, "modify header component size". He or she changed only header component and never touched any other components. However the naive difference detector unfortunately misunderstands "the entire page changed!"  because it can't recognize the simple Y-dimension translation.

### Goal
- provide alternative way to recognize difference

### Not goal
- replacement pixel-match: pixel-match is still great solution. It's simple and fast enough.  The new way should be optional.

### Algorithm
Using local features matching based region recognition. See https://github.com/reg-viz/improve_reg_diff

### TODO

- [x] Implement difference detector
- [ ] Invoke new engine(CLI)
- [ ] Invoke new engine(Browser)
- [ ] Introduce CLI option to tell reg-cli "enable smart diff"
- [ ] Hoist the above option to reg-suit/core option. User can set this using `regconfig.json`
- [ ] Add new view components to review the new comparison result
